//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zadatak_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSong
    {
        public int SongID { get; set; }
        public string SongName { get; set; }
        public string Author { get; set; }
        public string Duration { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Username { get; set; }
        public string Pasword { get; set; }
    }
}
